apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naeglelab-proteome-scout-test-pvc
  namespace: naeglelab
spec:
  storageClassName: naeglelab-proteome-scout-test-sc
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: naeglelab-proteome-scout-test-pv