apiVersion: v1
kind: Service
metadata:
  name: naeglelab-proteome-scout-test-service
  namespace: naeglelab
spec:
  selector:
    app: naeglelab-proteome-scout-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000