apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naeglelab-proteome-scout-prod-pvc
  namespace: naeglelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 1Gi
  volumeName: naeglelab-proteome-scout-prod-pv